# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lC8Lc-wPUzQ-AP9UaeXO6GORbD_RSgFq

Question 1 : Write a function ‘calculator’ that takes two variables as arguments and then ask the user to choose from the four options subtraction, addition, multiplication and division and give the output.
"""

def add(x, y):
    return x + y

def subtract(x, y):
    return x - y

def multiply(x, y):
    return x * y

def divide(x, y):
    return x / y
num1 = int(input("Enter first number: "))
num2 = int(input("Enter second number: "))

print("Select operation.")
print("1.Add")
print("2.Subtract")
print("3.Multiply")
print("4.Divide")
choice = input("Choose the option (1/2/3/4): ")
while True:
    if choice in ('1', '2', '3', '4'):
        

        if choice == '1':
            print("The addition of", num1 , "and", num2, "is", add(num1, num2))

        elif choice == '2':
            print("The substraction of", num1 , "and", num2, "is", subtract(num1, num2))

        elif choice == '3':
            print("The multiplication of", num1 , "and", num2, multiply(num1, num2))

        elif choice == '4':
            print("The division of", num1 , "and", num2, divide(num1, num2))
        break
    else:
        print("Invalid Input")

"""Question 2 : Write a function to find the factorial of a number taken from a user."""

def factorial(n):     
    if n == 0:
        return 1    
    return n * factorial(n-1)
num = int(input("Enter the Number "))
print("Factorial of", num, "is",
factorial(num))

"""question 3: Write a function to print all the odd numbers in between user defined range."""

def odd(start,end):
  return i
  
start = int(input("Start range "))
end = int(input("End range "))

for i in range(start,end+1):
  if i%2 != 0 :
     print(odd(start,end))

"""Question 4 : Write a function to find the smallest number from a user defined list."""

def num(n):
  return minimum_number

list1 = []
n=int(input("How many numbers you want to print "))
print("Enter the list of numbers ")
for i in range(0,n):
  element= int(input())
  list1.append(element)

minimum_number= min(list1)
print("The smallest number is ",num(n))

"""Question 5: Write a function to calculate area and perimeter of a rectangle using user defined length and breadth."""

def perimeter(x,y):
  return 2*(x+y)

def area(x,y):
  return x*y

x=int(input("Enter the length of retangle "))
y=int(input("Enter the breadth of rectangle "))

print("Perimeter of Rectangle is ", perimeter(x,y))
print("Area of Rectangke is ", area(x,y))

"""Question 6 : Write a function to check if the user defined number is even or not."""

def num(n):
 return n

n= int(input("Enter the number you want to check "))

if (n%2==0):
  print("The number is even ",num(n))
else:
  print("The number is not even")